---
# SPDX-License-Identifier: GPL-3.0-or-later

- name: "Restart systemd services"
  systemd:
    daemon_reload: "yes"
    name: "{{ item['name'] if item['name'] is defined else (item['src'] | basename | regex_replace('.j2', '')) }}"
    state: "restarted"
  listen: "restart_gitlab_services"
  with_items: "{{ gitlab_systemd_service_files }}"
  when:
    - "gitlab_systemd_managed | bool"
    - "gitlab_systemd_service_files is defined and gitlab_systemd_service_files is not none"
    - "item['react'] is defined and item['react'] | bool"
    - "ansible_service_mgr == 'systemd'"
